### ISSUE TITLE
在ubuntu22.04上启动失败

### ISSUE THREAD

**Issue by mx4994** [chika0801/tuic-install#1]
○ tuic.service - TUIC, TUIC's goal is to minimize the handshake latency as much as possible.
     Loaded: loaded (/etc/systemd/system/tuic.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Wed 2022-11-09 21:50:17 UTC; 5s ago
       Docs: https://github.com/EAimTY/tuic
    Process: 1384 ExecStart=/root/tuic -c /root/tuic_config.json (code=exited, status=0/SUCCESS)
   Main PID: 1384 (code=exited, status=0/SUCCESS)
        CPU: 1ms

Nov 09 21:50:17 ip-172-31-3-81 systemd[1]: Started TUIC, TUIC's goal is to minimize the handshake latency as much as possible..
Nov 09 21:50:17 ip-172-31-3-81 systemd[1]: tuic.service: Deactivated successfully.

内核版本：5.15.0-1022-aws
用Debian11没问题。

**Comment by chika0801** [comment]
你试试

https://github.com/EAimTY/tuic/releases/download/0.8.5/tuic-server-0.8.5-x86_64-linux-gnu

https://github.com/EAimTY/tuic/releases/download/0.8.5/tuic-server-0.8.5-x86_64-linux-musl

这2个，应该有1个能启动。

**Comment by chika0801** [comment]
> 0.85、0.84 gnu和musl都试了还是不行，如果不是那个[tuic.service](https://github.com/chika0801/tuic-install/blob/main/tuic.service)服务问题，那我就去TUIC项目反馈下。
> 
> 顺便问下那个连接端配置里，数据包大小1146是有什么考量嘛？就不说quic模式，就原生UDP模式，也是越接近MTU大小，传输效率越高。如果是光猫pppoe拨号的话，那么电脑数据包最大1492，跟1146差挺多的。

那个server文件你不用，就直接启动试试了。我用debian10 11试了的，ubuntu我平时没用。

1146是tuic的iss区 你翻翻iss提到的，1500有什么bug
