### ISSUE TITLE
由 sing-box 提供 Tun 模式（透明代理），v2rayN 管理配置



### ISSUE THREAD

**Issue by TingTing1990** [chika0801/tuic-install#3]
大佬，这种运行方式是客户端文件都用于sing-box和v2rayN？
那么设置好文件和在v2rayN里操作后是否只需要用命令行跑sing-box.exe就行了，不需要再操作v2rayN（开启系统代理或者Tun）？

**Comment by chika0801** [comment]
> 大佬，这种运行方式是客户端文件都用于sing-box和v2rayN？

tun环境是要用sing-box来提供。 然后你运行tuic你可以在cmd命令提示符窗口输入，用v2rayN的自定义是方便管理（切换）配置。不是必须要用v2rayN的意思。

**Comment by chika0801** [comment]
> 那么设置好文件和在v2rayN里操作后是否只需要用命令行跑sing-box.exe就行了，不需要再操作v2rayN（开启系统代理或者Tun）？

每次开电脑后，要手动启动sing-box，或参考这方法，我是手动启动的，因为有时候要调试sing-box配置，手动开和关方便。v2rayN倒是可以开机自启。

**Comment by TingTing1990** [comment]
@chika0801 感谢，就是用sing-box跑sing-box配置文件用tun模式监听所有流量并转发代理的流量给s5，v2rayN配置好客户端文件后需要打开系统代理或者Tun模式吗？还是说只要打开v2rayN就行了？

**Comment by chika0801** [comment]
你用v2rayn管理自定义配置，自定义配置内容是接sing-box发过来的本机socks端口时，v2rayn设置方法是那个添加自定义对话框 scoks处填0。n的自动配置系统代理选项我是一直用的清除系统代理

**Comment by TingTing1990** [comment]
> 你用v2rayn管理自定义配置，自定义配置内容是接sing-box发过来的本机socks端口时，v2rayn设置方法是那个添加自定义对话框 scoks处填0。n的自动配置系统代理选项我是一直用的清除系统代理

多谢！

**Comment by TingTing1990** [comment]
@chika0801 大佬，再次打扰下，如果sing-box出站是s5交给v2rayN，那么sing-box是不是要排除v2rayN？不然tun模式又劫持了v2rayN的流量

**Comment by chika0801** [comment]
> @chika0801 大佬，再次打扰下，如果sing-box出站是s5交给v2rayN，那么sing-box是不是要排除v2rayN？不然tun模式又劫持了v2rayN的流量

交给v2rayN，你在v2rayN里是用的各个core文件比如 xray.exe tuic.exe，所以我在sing-box的配置中排除了这些文件名的。至于v2rayN.exe本身，我不管过它。
