### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tgssaa** [chika0801/tuic-install#4]
大佬好，又来打扰了。
使用大佬这种方法搭建tuic非常便捷。请问如果想要修改UUID和密码，我尝试了修改jdon文件，之后重启，就无法使用了，我纯小白，能否请大佬指点一下？非常感谢！
再有，如果想要换端口，又改如何操作呢？

**Comment by chika0801** [comment]
uuid你是在专门的网站或用命令生成的吧，不是随便写。

uuid密码在服务端改后，客户端记着相应改。

**Comment by chika0801** [comment]
端口在两端配置中 

server 443 你把443换成你要的就是了

**Comment by tgssaa** [comment]
谢谢大佬！
